test:
  daemonize: true
  port: 5678
  workers: 2
  adminpwd: "admin"
  host: local

  transfer:
    notify_after_sec: 5
    mkdir: true
    tempfile: true
    overwrite: false
    timeout: 1800

  debug:
    ftp: false

  logs:
    thin:     "/tmp/rftpd-tests-thin.log"
    queue:    "/tmp/rftpd-tests-core.log"
    api:      "/tmp/rftpd-tests-core.log"
    workers:  "/tmp/rftpd-tests-work.log"
    jobs:     "/tmp/rftpd-tests-work.log"
    notify:   "/tmp/rftpd-tests-work.log"
    newrelic: "/tmp/rftpd-tests-newrelic.log"
